# Generated by Django 4.1.7 on 2023-03-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rarity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('physical_reduction', models.IntegerField(default=0)),
                ('supernatural_reduction', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('description', models.TextField()),
                ('opportunities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ring', models.CharField(max_length=5)),
                ('category', models.CharField(max_length=16)),
                ('type1', models.CharField(choices=[('1', 'Curse'), ('2', 'Flaw'), ('3', 'Interpersonal'), ('4', 'Infamy'), ('5', 'Mental'), ('6', 'Physical'), ('7', 'Scar'), ('8', 'Spiritual'), ('9', 'Virtue')], max_length=24)),
                ('type2', models.CharField(choices=[('1', 'Curse'), ('2', 'Flaw'), ('3', 'Interpersonal'), ('4', 'Infamy'), ('5', 'Mental'), ('6', 'Physical'), ('7', 'Scar'), ('8', 'Spiritual'), ('9', 'Virtue')], max_length=24, null=True)),
                ('type3', models.CharField(choices=[('1', 'Curse'), ('2', 'Flaw'), ('3', 'Interpersonal'), ('4', 'Infamy'), ('5', 'Mental'), ('6', 'Physical'), ('7', 'Scar'), ('8', 'Spiritual'), ('9', 'Virtue')], max_length=24, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rarity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('skill', models.CharField(max_length=12)),
                ('range', models.CharField(max_length=3)),
                ('damage', models.IntegerField()),
                ('deadliness', models.IntegerField()),
                ('one_hand', models.CharField(max_length=24, null=True)),
                ('two_hand', models.CharField(max_length=24, null=True)),
                ('qualities', models.ManyToManyField(to='Character_Menagement.itemquality')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rarity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('qualities', models.ManyToManyField(to='Character_Menagement.itemquality')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan', models.CharField(max_length=24)),
                ('family', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=24)),
                ('school', models.CharField(max_length=64)),
                ('notes', models.TextField(null=True)),
                ('status', models.IntegerField()),
                ('glory', models.IntegerField()),
                ('honor', models.IntegerField()),
                ('ninjo', models.CharField(max_length=240)),
                ('giri', models.CharField(max_length=240)),
                ('air', models.IntegerField(default=1)),
                ('earth', models.IntegerField(default=1)),
                ('fire', models.IntegerField(default=1)),
                ('water', models.IntegerField(default=1)),
                ('void', models.IntegerField(default=1)),
                ('aesthetics', models.IntegerField(default=0)),
                ('composition', models.IntegerField(default=0)),
                ('design', models.IntegerField(default=0)),
                ('smithing', models.IntegerField(default=0)),
                ('fitness', models.IntegerField(default=0)),
                ('meditation', models.IntegerField(default=0)),
                ('tactics', models.IntegerField(default=0)),
                ('melee', models.IntegerField(default=0)),
                ('ranged', models.IntegerField(default=0)),
                ('unarmed', models.IntegerField(default=0)),
                ('command', models.IntegerField(default=0)),
                ('courtesy', models.IntegerField(default=0)),
                ('games', models.IntegerField(default=0)),
                ('performance', models.IntegerField(default=0)),
                ('culture', models.IntegerField(default=0)),
                ('government', models.IntegerField(default=0)),
                ('sentiment', models.IntegerField(default=0)),
                ('theology', models.IntegerField(default=0)),
                ('medicine', models.IntegerField(default=0)),
                ('commerce', models.IntegerField(default=0)),
                ('labour', models.IntegerField(default=0)),
                ('seafaring', models.IntegerField(default=0)),
                ('skullduggery', models.IntegerField(default=0)),
                ('survival', models.IntegerField(default=0)),
                ('armour', models.ManyToManyField(to='Character_Menagement.armor')),
                ('equipment', models.ManyToManyField(to='Character_Menagement.equipment')),
                ('traits', models.ManyToManyField(to='Character_Menagement.trait')),
                ('weapons', models.ManyToManyField(to='Character_Menagement.weapon')),
            ],
        ),
        migrations.AddField(
            model_name='armor',
            name='qualities',
            field=models.ManyToManyField(to='Character_Menagement.itemquality'),
        ),
    ]
