# Generated by Django 4.1.7 on 2023-03-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Character_Menagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=24)),
                ('prerequisites', models.CharField(max_length=36)),
                ('description', models.TextField()),
                ('xp_cost', models.IntegerField(default=30)),
                ('activation', models.TextField()),
                ('effect', models.TextField()),
                ('opportunities', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='mastery_ability',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='school_ability',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='technique_categories',
            field=models.CharField(default='1', max_length=64),
            preserve_default=False,
        ),
    ]
