# Generated by Django 4.1.7 on 2023-03-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Character_Menagement', '0002_technique_character_mastery_ability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='techniques',
            field=models.ManyToManyField(to='Character_Menagement.technique'),
        ),
    ]
